### ISSUE TITLE
Training the ctpn and crnn Model for mobile

### ISSUE THREAD

**Issue by mrocr** [Sanster/DeepAndroidOcr#1]
@Sanster How did you train the mobile ctpn model & crnn model?

**Comment by Sanster** [comment]
Freeze tensorflow checkpoint to `pb` file, and use tensorflow-android to load the model

**Comment by mrocr** [comment]
Can you answer in more details of how did you create the models, along with:

- Which repositories in github that you used for creating the [models](https://github.com/Sanster/DeepAndroidOcr/tree/master/app/src/main/assets)?
- How did you get such small model sizes?
- How did you freeze the models?

**Comment by Sanster** [comment]
Which repositories in github that you used for creating the models?

> ctpn: https://github.com/Sanster/tf_ctpn
> crnn: https://github.com/Sanster/tf_crnn

How did you get such small model sizes?
> use small cnn(mobilenet)；tensorflow freeze_graph will make the model small

How did you freeze the models?
> ctpn: https://github.com/Sanster/tf_ctpn/blob/master/tools/freeze_graph.py
> crnn: https://github.com/Sanster/tf_crnn/blob/master/tools/freeze_graph.py

You can check  tensorflow document for more detail

**Comment by luqiang6q** [comment]
@Sanster hello, how do you deploy the model to the anaroid? use tensorflow-lite or mace or ncnn?

**Comment by Sanster** [comment]
org.tensorflow:tensorflow-android:1.9.0
